knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(GOOGLE_CLIENT_ID)%'
            client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
            redirect_route: api_auth_oauth_check
            redirect_params:
                provider: google
            access_type: offline
            hosted_domain: ~
            user_fields: null

        facebook:
            type: facebook
            client_id: '%env(FACEBOOK_CLIENT_ID)%'
            client_secret: '%env(FACEBOOK_CLIENT_SECRET)%'
            redirect_route: api_auth_oauth_check
            redirect_params:
                provider: facebook
            graph_api_version: v12.0
